version: '3'

services:
  pubnubcoin.com:
    build: http2
    image: http2
    expose:
      - "4443"

  pubnub:
    build: ./SDKs/${SDK}
    image: pubnub-${SDK}
    links:
      - pubnubcoin.com
    depends_on:
      - pubnubcoin.com
    volumes:
      - ./SDKs/${SDK}:/code
    working_dir: /code
